### ISSUE TITLE
Discrepancy between permissions listed on ATN and permissions requested by the add-on during install

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/addons-server#259]
This was reported for the q-note add-on, but is valid for all add-ons which are using Experiments.

The permission information popup on ATN does not state, if the add-on uses Experiments. In Thunderbird itself we do not prompt for any individual WebExtension permissions, if the add-on uses Experiments, but simply ask for the full-access permission.

We should at least list the full-access permission in that popup on ATN as well. If possible, drop the other permissions altogether, to be consistent with the permission-install-prompt

**Comment by jobisoft** [comment]
Today I had another reviewer, who blamed this on an add-on, and gave a 1 star review, even though the add-on is not able to fix this (besides mentioning the required full access permission in its description)

**Comment by MelissaAutumn** [comment]
Thanks for the report and re-ping. I'll get to this as soon as I can.

**Comment by MelissaAutumn** [comment]
Okay confirmed working in test environment, if an addon file is marked as "is_experiment==True" it will show the "Permissions" modal link, and only show the following:

<img width="603" alt="image" src="https://github.com/thunderbird/addons-server/assets/97147377/f44ddb6f-9e73-4016-933d-7151147b7804">
<img width="598" alt="image" src="https://github.com/thunderbird/addons-server/assets/97147377/0a639dfc-14eb-4179-9b26-dc93d596ba53">

L10n only applies to English, Italian, French, German, and Polish.
