### ISSUE TITLE
Donation link cannot point to https://www.thunderbird.net/donate/

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/addons-server#263]
The donation links for add-ons can go to paypal, liberapay and the mozilla foundation, but not to

https://www.thunderbird.net/donate/

**Comment by MelissaAutumn** [comment]
Easy fix, I believe we just need to add the url to https://github.com/thunderbird/addons-server/blob/master/src/olympia/constants/base.py#L220

Any objections @Sancus ?
