### ISSUE TITLE
Uploading fails with a 502 error

### ISSUE THREAD

**Issue by dillenger** [thunderbird/addons-server#268]
Uploading currently fails with a 502 (bad gateway) error, sometimes even logging in fails.

Cloudflare (Amsterdam) blames addons.thunderbird.net but I can't check that, trying again doesn't help.

![image](https://github.com/thunderbird/addons-server/assets/571067/ecb302c8-3a12-4556-8f66-411494228b40)

**Comment by MelissaAutumn** [comment]
Thanks for the report, we're looking into this.

**Comment by MelissaAutumn** [comment]
Sorry for the delay, this should be resolved now. Thanks for your patience!
