### ISSUE TITLE
Is statistics server down again?

### ISSUE THREAD

**Issue by KNHaw** [thunderbird/addons-server#269]
### Describe the problem and steps to reproduce it:
When looking at the [statistics for my add-on](https://addons.thunderbird.net/en-US/thunderbird/addon/obsidianclipper/statistics/usage/versions/?last=30) I'm seeing zero users since Monday (20240206 to 20240209 zeroes). I saw a similar hiccup last week (20240204). I found [some similar issues](https://github.com/thunderbird/addons-server/issues/245) that are now closed. I'm also seeing the same on a few other add-ons I bothered to check ([here](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderstats/statistics/usage/versions/?last=30) and [here](https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/statistics/usage/versions/?last=30))

![stats2](https://github.com/thunderbird/addons-server/assets/138092261/7b691cb9-e214-4470-a9f2-14ae7053ba52)

### What happened?
It appears that statistics are offline for all add-ons for the past week. Did someone spill their beer on the server? (*GRIN*)

### What did you expect to happen?
Get statistics working again.

### Anything else we should know?

Is anyone taking taking a long term look at this?

**Comment by KNHaw** [comment]
OK. Looks like we have data again. I'll close the issue, but do wonder if we have a long term fix for this.

**Comment by Sancus** [comment]
> OK. Looks like we have data again. I'll close the issue, but do wonder if we have a long term fix for this.

Nothing in software is ever "long term fixed", lol. There was a problem in the logs that was breaking the parser and it's fixed now. Stuff changes constantly and there will probably be problems again in the future.

**Comment by KNHaw** [comment]
@Sancus Thanks for your response. My concern wasn't so much that it broke but thar it stayed broke for nearly a week. Any way we can put in an alert/alarm that sends an email if everyone goes to zero or the parser throws an error? Justa thought.

**Comment by Sancus** [comment]
> @Sancus Thanks for your response. My concern wasn't so much that it broke but thar it stayed broke for nearly a week. Any way we can put in an alert/alarm that sends an email if everyone goes to zero or the parser throws an error? Justa thought.

I was aware it broke but was out office at the time. It took about 3-4 hours of investigation to figure out what was going on and deploy a fix. And unfortunately I'm something of a knowledge bottleneck on the stats stuff right now. That part will get better. But I should note that the data will always be fully caught up and since stats don't affect the functionality of the site it's not treated as a critical outage.
