### ISSUE TITLE
Emails are coming from the future (wrong server time?)

### ISSUE THREAD

**Issue by Juraj-Masiar** [thunderbird/addons-server#276]
### Describe the problem and steps to reproduce it:
Emails from `thunderbird.net` have wrong time, they are 6 minutes ahead of time.

![image](https://github.com/thunderbird/addons-server/assets/6358971/a8708539-2cf3-4f3d-bd4b-13c9cc597246)

![image](https://github.com/thunderbird/addons-server/assets/6358971/6da589ba-47bc-48c6-aeb4-65bfe3f5a530)

Nothing serious, just thought you should know.

**Comment by Sancus** [comment]
One of the instance clocks was out of whack, fixed this a while ago by ensuring [chronyd is installed](https://github.com/thunderbird/thundernest-ansible/blob/master/addons/playbooks/deploy-instance.yml#L101).
