### ISSUE TITLE
Can't access dictionary

### ISSUE THREAD

**Issue by hewhowaspapa** [thunderbird/addons-server#278]
I installed the dictionary 'add on' in Firefox: English United States Dictionary
English United States (en-US) Dictionary as shipped with Firefox 115 ESR.

It installed fine but there is no way to access it: it doesn't have a toolbar icon, it is not available from the Tools menu, it does not show up in a right-click or appear in the search engine.

what do I need to do to get an 'add on' that works?

grayson.rbg@gmail.com

**Comment by Sancus** [comment]
This repository has nothing to do with Firefox, it's for Thunderbird.

Also dictionaries are only used for spellcheck, not to search on or anything like that.
