### ISSUE TITLE
The plugin's post validator has stopped displaying the warnings and errors it was displaying before and is now only displaying an error.

### ISSUE THREAD

**Issue by joaquinlefebvre** [thunderbird/addons-server#290]
### What happened?
Uploading a .zip file through the page https://addons.thunderbird.net/es/developers/addon/[name]/versions/submit/ now shows the error that I attached in the images, but 4 or so ago 5 days it showed the errors and warnings that it really has and I have been able to reduce them. Now when it shows nothing more than this error, I can't continue with the publishing process.
### What did you expect to happen?
Show the same warnings and errors that it showed 4 or 5 days before.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://github.com/thunderbird/addons-server/assets/94112683/a96dadcf-db89-4240-bc31-b714307c97b7)
![image](https://github.com/thunderbird/addons-server/assets/94112683/23be2b7a-43c0-4b2f-9cd4-9987441fb2c3)

I have the 'dist.zip' but I guess I shouldn't link it here directly. Can I get it to you somehow?

Thank you very much in advance

**Comment by joaquinlefebvre** [comment]
> Hey there, what is your addon called?

Hi.
The name is "lex-on-conecta"

**Comment by MelissaAutumn** [comment]
Thanks, looks like something server-side. We'll look at it.

**Comment by MelissaAutumn** [comment]
Heya @joaquinlefebvre,

We've tweaked some things on the backend, and it should be back to how it was before!

Let me know if it doesn't work.

**Comment by joaquinlefebvre** [comment]
@MelissaAutumn:
It works perfectly. 
You solved it really quickly.

Thanks a lot.
