### ISSUE TITLE
Add-ons downloads count is always zero

### ISSUE THREAD

**Issue by micz** [thunderbird/addons-server#291]
### Describe the problem and steps to reproduce it:
In the statistics panel the download are always zero for all my add-ons.

**Example**: https://addons.thunderbird.net/it/thunderbird/addon/thunderai/

From the statistics dashboard:
![immagine](https://github.com/thunderbird/addons-server/assets/61795/36f0b5af-5a34-499c-9494-20a4f688eba6)

Download dashboard:
![immagine](https://github.com/thunderbird/addons-server/assets/61795/95b0fa98-6e30-43fc-9546-e2c4d1d0b8f0)

### What happened?
The downloads are always zero.

### What did you expect to happen?
To count some download, given that the daily users are always growing.

**Comment by MelissaAutumn** [comment]
After a bit of investigating, it seems we don't actually support the infrastructure to calculate downloads right now. This may change in the future, so I'm tagging this as an enhancement.

**Comment by Sancus** [comment]
See https://github.com/thunderbird/addons-server/issues/80
