### ISSUE TITLE
Thunderbird Add-on Not Passing Validation on min/max version

### ISSUE THREAD

**Issue by 5dma** [thunderbird/addons-server#300]
### Describe the problem and steps to reproduce it:
I created an add-on for Thunderbird. You can see the source code at [https://github.com/5dma/remove_query_parameter](https://github.com/5dma/remove_query_parameter).

My add-on is not passing the min/max version test in the linter at [Submit a New Add-on](https://addons.thunderbird.net/en-US/developers/addon/submit/upload-unlisted).

### What happened?

Uploading the .xpi file gives the following errors:
```
Your add-on failed validation with 1 error.

Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?
```
However, the full validation results report shows 0 errors, two warnings, and 0 notices. The two warnings are not germane to version numbers.

My `browser_specific_settings` object is as follows:
```json
"browser_specific_settings": {
	"gecko": {
		"id": "mark@lautman.net",
		"strict_min_version": "115.12",
		"strict_max_version": "115.*"
	}
}
```
### What did you expect to happen?

I would expect one of the following:

- If I get an error message, the same error message should appear in the validation report.
- If the error messages says that I'm specifying an unsupported version, there should be a link to the versions that are supported.

**Comment by MelissaAutumn** [comment]
Hey there we generally don't import or add point releases, so if you adjust the strict_min_version to 115.0 it should work. 

Here's a list of available values: https://addons.thunderbird.net/en-US/thunderbird/pages/appversions/
