### ISSUE TITLE
No Sound, no Details :(

### ISSUE THREAD

**Issue by gooly** [thunderbird/addons-server#306]
### Describe the problem and steps to reproduce it:
Win 10, Thunderbird 128.1.1esr (64-Bit)

I installed NTFNTF v1.2.0 dtd. 26. August 2024
and setup several folders. I got mail but NTFNTF was quiet and I got no notice.
This is my setting:
[Can't add my screeenshots :(]
1)
So under "Lokale Ordner" (German for local folder?)
Sound: "You Got Mail" Details: "Name & Message" {max possible}
It plays the sound - I can hear it.

2)
I marked/enabled several folder of "Lokale Ordner" but nothing happened except there appeared a little yellow triangle after a new mails was saved there -- but no "Sound", no "Name" and no "Details"

:(
PS the screenshot were not accepted ??

**Comment by Sancus** [comment]
Please contact the add-on author directly for support, we don't provide support for third party add-ons. It seems their repository is here: 

https://gitlab.com/dan-sullivan/ntfntf/-/issues
