### ISSUE TITLE
TB sometimes takes an art break

### ISSUE THREAD

**Issue by B-Gruen** [thunderbird/addons-server#307]
I can check this by right-clicking on any folder in the list. If QNote is deactivated, the desired window is displayed immediately.

https://www.thunderbird-mail.de/forum/thread/95215-qnote-in-128-mit-bug/

**Comment by Sancus** [comment]
We don't provide support for individual add-ons here, this repository is for the site itself. You can find the qnote support site here: https://github.com/mlazdans/qnote
