### ISSUE TITLE
mailmerge pause between sending emails

### ISSUE THREAD

**Issue by mlrsystems-terry** [thunderbird/addons-server#314]
when using send later option the pause between email sends does not happen when you right click on outbox and select send unsent messages.
If there really is a way to do this I have not been able to find it.
Thanks
Terry

**Comment by Sancus** [comment]
This issue tracker is for problems with the addons website, not for support or bug reports about add-ons. For that you must contact the author of the add-on. If you're looking for Send Later, that would be here: https://github.com/extended-thunder/send-later/discussions
